version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    ignore:
      # The USWDS version should be managed manually
      # and coordinated with the ReactUSWDS version.
      - dependency-name: "uswds"
  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/deploy-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/deploy-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/image-scan"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
