output: table
ignore:
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown
  # Ignore the following SnakeYAML vulnerabilities. The claimant intake
  # application does not use SnakeYAML to parse untrusted input.
  # See the discussion at https://github.com/spring-projects/spring-boot/issues/32221
  - vulnerability: GHSA-c4r9-r8fh-9vj2
    package:
      name: snakeyaml
  - vulnerability: GHSA-hhhw-99gj-p3c3
    package:
      name: snakeyaml
  - vulnerability: GHSA-3mc7-4q67-w48m
    package:
      name: snakeyaml
  - vulnerability: GHSA-98wm-3w3q-mw94
    package:
      name: snakeyaml
  - vulnerability: GHSA-9w3m-gqgf-c4p9
    package:
      name: snakeyaml
  - vulnerability: GHSA-w37g-rhq8-7m4j
    package:
      name: snakeyaml
  # Ignore the following OpenSSL vulnerabilities until patches are available
  # in the application's base images
  # https://github.com/newjersey/dol-ui-claimant-intake/issues/1463
  - vulnerability: CVE-2022-2097
    package:
      name: libssl1.1
  - vulnerability: CVE-2022-4304
    package:
      name: libssl1.1
  - vulnerability: CVE-2022-4450
    package:
      name: libssl1.1
  - vulnerability: CVE-2023-0215
    package:
      name: libssl1.1
  - vulnerability: CVE-2023-0286
    package:
      name: libssl1.1
  - vulnerability: CVE-2022-2097
    package:
      name: openssl
  - vulnerability: CVE-2022-4304
    package:
      name: openssl
  - vulnerability: CVE-2022-4450
    package:
      name: openssl
  - vulnerability: CVE-2023-0215
    package:
      name: openssl
  - vulnerability: CVE-2023-0286
    package:
      name: openssl
