output: table
ignore:
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown
  # Ignore the following SnakeYAML vulnerabilities. The claimant intake
  # application does not use SnakeYAML to parse untrusted input.
  # See the discussion at https://github.com/spring-projects/spring-boot/issues/32221
  - vulnerability: GHSA-mjmj-j48q-9wg2
    package:
      name: snakeyaml
