output: table
ignore:
  - fix-state: not-fixed
  - fix-state: wont-fix
  - fix-state: unknown
  # We use dependabot to monitor for javascript dependency updates
  - package:
      type: npm
  # Ignore the following SnakeYAML vulnerabilities. The claimant intake
  # application does not use SnakeYAML to parse untrusted input.
  # See the discussion at https://github.com/spring-projects/spring-boot/issues/32221
  - vulnerability: GHSA-c4r9-r8fh-9vj2
    package:
      name: snakeyaml
  - vulnerability: GHSA-hhhw-99gj-p3c3
    package:
      name: snakeyaml
  - vulnerability: GHSA-3mc7-4q67-w48m
    package:
      name: snakeyaml
  - vulnerability: GHSA-98wm-3w3q-mw94
    package:
      name: snakeyaml
  - vulnerability: GHSA-9w3m-gqgf-c4p9
    package:
      name: snakeyaml
  # Ignore the following jackson-databind vulnerability. There is not
  # a proper release available at this time fixing the vulnerability.
  # The claimant intake application does not use UNWRAP_SINGLE_VALUE_ARRAYS.
  # See the discussion at https://github.com/spring-projects/spring-boot/issues/32583
  - vulnerability: GHSA-jjjh-jjxp-wpff
    package:
      name: jackson-databind
