---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # TODO: Add python specific checks alongside python code.
  #       (fix-encoding-pragma, debug-statements, requirements-txt-fixer, check-ast)
  #       Check ARPAUI for parity (https://github.com/USDOLEnterprise/ARPAUI/blob/main/.pre-commit-config.yaml)

  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: gen-docs
        args: ["docs/adr"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-toc
        exclude: >
          (?x)^(
            .github/ISSUE_TEMPLATE/.*.md|
          )$

  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
            .github/ISSUE_TEMPLATE/.*.md|
          )$

  - repo: local
    hooks:
      - id: eslint-client
        name: eslint-client
        entry: yarn --cwd client lint
        language: node
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false
      - id: eslint-e2e
        name: eslint-e2e
        entry: yarn --cwd e2e lint
        language: node
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false
      - id: server-spotless
        name: server-spotless
        entry: make server-spotless
        language: system
