version: "3.9"

services:
  client:
    build:
      context: client
    image: dol-ui-client:latest
    read_only: true
    ports:
      - "3000:3000"
  server:
    build:
      context: server
    image: dol-ui-server:latest
    read_only: true
    tmpfs: /tmp
    ports:
      - "8080:8080"
