version: "3.9"

services:
  client:
    build:
      context: client
    image: dol-ui-client:latest
    container_name: dol-ui-client
    networks:
      - front-tier
    read_only: true
    ports:
      - "3000:3000"
  server:
    build:
      context: server
    image: dol-ui-server:latest
    container_name: dol-ui-server
    networks:
      - back-tier
    read_only: true
    tmpfs: /tmp
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT_URL: http://localstack:4566
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: db
  db:
    image: postgres:14.3
    container_name: dol-ui-db
    restart: always
    networks:
      - back-tier
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localdev-postgres
      POSTGRES_PASSWORD: localdev-postgres
    volumes:
      - db:/var/lib/postgresql/data
  localstack:
    container_name: dol-ui-localstack
    image: localstack/localstack:1.0.4
    networks:
      - back-tier
    ports:
      - "4566:4566"
    volumes:
      - "localstack:/var/lib/localstack"
      - "./scripts/aws-init:/docker-entrypoint-initaws.d"

networks:
  front-tier:
    name: dol-ui-front-tier
  back-tier:
    name: dol-ui-back-tier

volumes:
  db:
    name: dol-ui-db
  localstack:
    name: dol-ui-localstack
