version: "3.9"

services:
  nginx:
    build:
      context: nginx
    image: dol-ui-nginx:latest
    container_name: dol-ui-nginx
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - "8443:8443"
  client:
    build:
      context: client
      args:
        - NEXT_PUBLIC_SERVER_BASE_URL=https://sandbox-claimant-intake:8443
    image: dol-ui-client:latest
    container_name: dol-ui-client
    networks:
      - front-tier
    read_only: true
    env_file: client/.env
    environment:
      - NEXTAUTH_URL=https://sandbox-claimant-intake:8443
    ports:
      - "3000:3000"
  server:
    build:
      context: server
    image: dol-ui-server:latest
    container_name: dol-ui-server
    networks:
      - back-tier
    read_only: true
    ports:
      - "8080:8080"
    volumes:
      - server:/tmp/app
    env_file: server/.env
    environment:
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT_URL: http://localstack:4566
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-}
      DB_HOST: db
      DB_PORT: 5432
      MOCK_LOOPS_HOST: http://localhost:9090
      MOCK_LOOPS_PATH: /mockloopspath
      LOOPS_HOST: ${LOOPS_HOST:-}
      LOOPS_PATH: ${LOOPS_PATH:-}

  db:
    image: postgres:14.3
    container_name: dol-ui-db
    restart: always
    networks:
      - back-tier
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localdev-postgres
      POSTGRES_PASSWORD: localdev-postgres
    volumes:
      - db:/var/lib/postgresql/data
  localstack:
    container_name: dol-ui-localstack
    image: localstack/localstack:1.0.4
    networks:
      - back-tier
    ports:
      - "4566:4566"
    volumes:
      - "localstack:/var/lib/localstack"
      - "./scripts/aws-init:/docker-entrypoint-initaws.d"
  wiremock:
    container_name: dol-ui-wiremock
    image: wiremock/wiremock:2.35.0
    networks:
      - back-tier
    ports:
      - "9090:8080"
    volumes:
      - "./wiremock:/home/wiremock"
networks:
  front-tier:
    name: dol-ui-front-tier
  back-tier:
    name: dol-ui-back-tier

volumes:
  db:
    name: dol-ui-db
  localstack:
    name: dol-ui-localstack
  server:
    name: dol-ui-server
