---
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health
server:
  servlet:
    context-path: /api

spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog.yaml"
