---
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=verify-full&sslrootcert=/app/certs/us-east-1-bundle.pem
    username: app_user
    type: nj.lwd.ui.claimantintake.configuration.RdsIamHikariDataSource
    hikari:
      max-lifetime: 840000
