name: Image Vulnerability Scan
description: Run image vulnerability scans
inputs:
  image:
    description: The docker image to scan
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5
      env:
        TRIVY_OFFLINE_SCAN: true
      with:
        scan-type: "image"
        image-ref: ${{inputs.image}}
        format: "table"
        exit-code: "1"
        ignore-unfixed: true
        vuln-type: "os,library"
        security-checks: "vuln,secret"
    # Commenting out the grype scan until the following issue is resolved:
    # https://github.com/anchore/scan-action/issues/211
    # - name: Run Anchore vulnerability scan
    #   uses: anchore/scan-action@84aa2c1d0eba986ed2274869c27f1e35a625449f
    #   with:
    #     image: ${{inputs.image}}
    #     severity-cutoff: "negligible"
    #     output-format: "table"
