name: Lint, Build, and Test
description: Lint and run unit tests
inputs:
  JAVA_VERSION:
    description: The java version of the codebase
    required: true
  NODE_VERSION:
    description: The java version of the codebase
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
      with:
        key: v1-pre-commit-dot-cache-${{ hashFiles('.pre-commit-config.yaml') }}
        path: ~/.cache/pre-commit

    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: "yarn"
        cache-dependency-path: "**/yarn.lock"

    - name: Install client dependencies
      run: make client-deps
      shell: bash

    - name: Install e2e dependencies
      run: make e2e-deps
      shell: bash

    - name: Set up Java
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: "temurin"

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

    - name: Install server dependencies
      run: make server-deps
      shell: bash

    - name: Lint
      run: make lint
      shell: bash

    - name: Run JUnit tests
      run: make server-test
      shell: bash

    - name: Verify server test coverage
      run: make server-test-coverage-check
      shell: bash

    - name: Run server checks
      run: make server-check
      shell: bash

    - name: Check client Typescript compilation
      run: make client-compile-check
      shell: bash

    - name: Run Jest tests
      run: make client-test-coverage
      shell: bash
