env:
  browser: true
  node: true
  commonjs: true
  es2021: true
  jest: true
parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:security/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
root: true
settings:
  react:
    version: '18'
rules:
  'react/react-in-jsx-scope': 'off'
  'react/jsx-filename-extension':
    [1, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  'react/prop-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-unused-vars': ['error']
ignorePatterns:
  - '!.storybook/'
