export const ISO_8601_DATE = 'YYYY-MM-DD'
export const USER_FACING_DATE_INPUT_FORMAT = 'MM-DD-YYYY'
export const USER_POOL_DATE_FORMAT = 'MM/DD/YYYY'
export const DATE_TIME_FORMAT = 'MMMM D, YYYY hh:mm:ss a'
export const DATE_FORMAT = 'MMMM D, YYYY'
export const EXPIRES_AT_FORMAT = 'MMMM D'
