name: Create Cognito URLs
description: For deployment previews, create logout and redirect urls and add them to cognito and ssm
inputs:
  aws-role-to-assume:
    description: The AWS role to assume
    required: true
  base-url:
    description: Url for the deployment preview
    required: true
  pr-number:
    description: Pull request number for ssm
    required: true
  cognito-client-id:
    description: AWS ID for the congnito user pool client
    required: true
  cognito-user-pool-id:
    description: AWS ID for the cognito user pool
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: us-east-1

    - name: Check if ssm parameter exists
      id: check-ssm
      env:
        PARAMETER_NAME: /dol-ui-claimant-intake-dev/nextauth-url/${{ inputs.pr-number }}
      shell: bash
      run: |
        SSM_CHECK_COUNT=$( aws ssm get-parameter \
        --region us-east-1 \
        --name "$PARAMETER_NAME" \
        --with-decryption \
        | grep -c "Value" )
        echo "ssm-count=$SSM_CHECK_COUNT" >> $GITHUB_OUTPUT

    - name: Create ssm parameter
      if: steps.check-ssm.outputs.ssm-count == '0'
      env:
        PARAMETER_NAME: /dol-ui-claimant-intake-dev/nextauth-url/${{ inputs.pr-number }}
        PARAMETER_VALUE: ${{ base-url }}
      shell: bash
      run: |
        aws ssm put-parameter \
        --region us-east-1 \
        --name "$PARAMETER_NAME" \
        --value "$PARAMETER_VALUE" \
        --type "SecureString"

    - name: Get user pool client json
      if: steps.check-ssm.outputs.ssm-count == '0'
      id: client-json
      env:
        USER_POOL_ID: ${{ inputs.cognito-user-pool-id }}
        CLIENT_ID: ${{ inputs.cognito-client-id }}
      shell: bash
      run: |
        aws cognito-idp describe-user-pool-client \
        --region us-east-1 \
        --user-pool-id $USER_POOL_ID \
        --client-id $CLIENT_ID \
        --output json >> user-pool-client.json

    - name: Update user pool client json
      if: steps.check-ssm.outputs.ssm-count == '0'
      id: updated-json
      env:
        CALLBACK_URL: ${{ base-url }}/api/auth/callback/cognito
        SIGNOUT_URL: ${{ base-url }}
      shell: bash
      run: |
        jq \
        --arg CALLBACK_URL "$CALLBACK_URL" \
        --arg SIGNOUT_URL "$SIGNOUT_URL" \
        '.UserPoolClient.CallbackURLs += [$CALLBACK_URL] | .UserPoolClient.LogoutURLs += [$SIGNOUT_URL]' \
        user-pool-client.json >> updated-upc.json

    - name: Update cognito user pool client callback and signout with deployment preview URL
      if: steps.check-ssm.outputs.ssm-count == '0'
      env:
        UPDATED_JSON: ${{ fromJSON(updated-upc.json) }}
      shell: bash
      run: |
        aws cognito-idp update-user-pool-client \
        --cli-input-json $UPDATED_JSON
