on:
  pull_request:
  push:
    branches:
      - main

# Cancel redundant builds on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Test and Lint
jobs:
  lint-build-and-test:
    name: Lint, build, and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          key: v1-pre-commit-dot-cache-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Lint
        run: make lint

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.2.0
          cache: "yarn"
          cache-dependency-path: "client/yarn.lock"

      - name: Install dependencies
        run: make client-deps-ci

      - name: Check Typescript compilation
        run: make client-compile-check

      - name: Run Jest tests
        run: make client-test

  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: client
          tags: dol-ui-client:latest
          push: false
          outputs: type=docker,dest=/tmp/client-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-image
          path: /tmp/client-image.tar
          retention-days: 1

  docker-push:
    name: Docker push
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: client-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/client-image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push image to Amazon ECR
        id: tag-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dol-ui-claimant-intake-client-dev
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag dol-ui-client:latest "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: config/ecs/task-definition.json
          container-name: dol-ui-claimant-intake-client-dev
          image: ${{ steps.tag-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: dol-ui-claimant-intake-client
          cluster: dol-ui-claimant-intake-dev
          wait-for-service-stability: true
