name: Test and Lint

on:
  pull_request:
  push:
    branches:
      - main

# Cancel redundant builds on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-build-and-test:
    name: Lint, build, and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          key: v1-pre-commit-dot-cache-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Set up Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16.16.0
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install client dependencies
        run: make client-deps

      - name: Install e2e dependencies
        run: make e2e-deps

      - name: Set up Java
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: "17.0.4+8"
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Install server dependencies
        run: make server-deps

      - name: Lint
        run: make lint

      - name: Run JUnit tests
        run: make server-test

      - name: Run server checks
        run: make server-check

      - name: Check client Typescript compilation
        run: make client-compile-check

      - name: Run Jest tests
        run: make client-test-coverage

  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16.16.0
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install e2e dependencies
        run: make e2e-deps

      - name: Check e2e Typescript compilation
        run: make e2e-compile-check

      - name: Add /etc/hosts entry
        run: echo '127.0.0.1  sandbox-claimant-intake' | sudo tee -a /etc/hosts

      - name: Make nginx cert
        run: make nginx-cert

      - name: Start CI docker container
        run: make ci-up
        env:
          DOCKER_BUILDKIT: 1

      - name: Run Cypress tests
        run: make e2e-ci-test

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: cypress-artifacts
          path: |
            /home/runner/work/dol-ui-claimant-intake/dol-ui-claimant-intake/e2e/cypress/screenshots/
            /home/runner/work/dol-ui-claimant-intake/dol-ui-claimant-intake/e2e/cypress/videos/
          retention-days: 1

      - name: Stop CI docker container
        run: make ci-down

      - name: Scan server image
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/image-scan
        with:
          image: dol-ui-server:latest

      - name: Scan client image
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/image-scan
        with:
          image: dol-ui-client:latest
