name: Cache Docker Images

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cache-images:
    runs-on: ubuntu-latest
    environment: ci

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_CI }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325

      - name: Build & Push dev-deps client image
        id: build-image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          push: true
          context: client
          tags: ${{ steps.login-ecr.outputs.registry }}/dol-ui-claimant-intake-client-ci:dev-deps
          cache-to: type=inline
          target: dev-deps

      - name: Build & Push prod-deps client image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          push: true
          context: client
          tags: ${{ steps.login-ecr.outputs.registry }}/dol-ui-claimant-intake-client-ci:prod-deps
          cache-to: type=inline
          target: prod-deps

      - name: Build & Push builder client image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          push: true
          context: client
          tags: ${{ steps.login-ecr.outputs.registry }}/dol-ui-claimant-intake-client-ci:builder
          cache-to: type=inline
          target: builder

      - name: Build & Push builder server image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          push: true
          context: server
          tags: ${{ steps.login-ecr.outputs.registry }}/dol-ui-claimant-intake-server-ci:builder
          cache-to: type=inline
          target: builder
