name: Deploy

on:
  workflow_run:
    workflows:
      - Test and Lint
    types:
      - completed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dev-client-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Deploy client
        uses: ./.github/actions/deploy-client
        with:
          deploy-env: dev
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          server-base-url: ${{ secrets.NEXT_PUBLIC_SERVER_BASE_URL }}

  dev-server-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construct image tag
        id: construct-image-tag
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_COMMIT: ${{ github.sha }}
        run: |
          BRANCH_PREFIX="$GIT_BRANCH"
          # use a generic prefix for all non-main branches
          if [[ "$BRANCH_PREFIX" != "main" ]]; then
            BRANCH_PREFIX="branch"
          fi
          BUILD_TIME=$(date '+%Y%m%d%H%M%S')
          IMAGE_TAG="${BRANCH_PREFIX}-${GIT_COMMIT}-${BUILD_TIME}"
          echo "::set-output name=image-tag::$IMAGE_TAG"

      - name: Build, tag, and push image to Amazon ECR (server-util)
        id: build-util-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dol-ui-claimant-intake-server-util-dev
          IMAGE_TAG: ${{ steps.construct-image-tag.outputs.image-tag }}
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" --build-arg IMAGE_TAG="$IMAGE_TAG" ops/server-util
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Build, tag, and push image to Amazon ECR (server)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dol-ui-claimant-intake-server-dev
          IMAGE_TAG: ${{ steps.construct-image-tag.outputs.image-tag }}
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" server
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy server
        uses: ./.github/actions/deploy-server
        with:
          deploy-env: dev
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          server-image: ${{ steps.build-image.outputs.image }}
          server-util-image: ${{ steps.build-util-image.outputs.image }}

      - name: Write server image tag to file
        env:
          IMAGE_TAG: ${{ steps.construct-image-tag.outputs.image-tag }}
        run: |
          mkdir -p tmp/artifact
          echo -n "$IMAGE_TAG" > tmp/artifact/server_image_tag.txt

      - uses: actions/upload-artifact@v3
        with:
          name: server-image-tag
          path: tmp/artifact/server_image_tag.txt
          retention-days: 1

  test-client-deploy:
    needs: [dev-client-deploy, dev-server-deploy]
    runs-on: ubuntu-latest
    environment: test

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Deploy client
        uses: ./.github/actions/deploy-client
        with:
          deploy-env: test
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_TEST }}
          server-base-url: ${{ secrets.NEXT_PUBLIC_SERVER_BASE_URL }}

  test-server-deploy:
    needs: [dev-client-deploy, dev-server-deploy]
    runs-on: ubuntu-latest
    environment: test

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: server-image-tag
          path: tmp/artifact

      - name: Get server image tag
        id: get-image-tag
        run: |
          IMAGE_TAG=$(cat tmp/artifact/server_image_tag.txt)
          echo "::set-output name=image-tag::$IMAGE_TAG"

      # The server images do not need to be rebuilt in each environment. Instead,
      # promote and reuse the server images from the dev environment.
      # Server configurations that need to vary between environments can be set
      # at runtime through environment variables and/or spring boot profiles.
      - name: Deploy server
        uses: ./.github/actions/deploy-server
        with:
          deploy-env: test
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_TEST }}
          server-image: ${{ secrets.ECR_REGISTRY_DEV}}/dol-ui-claimant-intake-server-dev:${{ steps.get-image-tag.outputs.image-tag }}
          server-util-image: ${{ secrets.ECR_REGISTRY_DEV}}/dol-ui-claimant-intake-server-util-dev:${{ steps.get-image-tag.outputs.image-tag }}
