name: Deploy Preview Destroy

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pull_request:
        required: true
        description: Pull Request Issue Number to be destroyed.
      branch:
        required: true
        description: Tag or branch to be deployed.

# Stop building resources if the branch is closed before preview is deployed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    outputs:
      server-base-url: ${{ steps.server-base-url.outputs.server-base-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Compose server base url
        id: server-base-url
        env:
          GIT_BRANCH: ${{ steps.branch-name.outputs.current_branch ||  github.event.inputs.branch }}
          DEV_SERVER_BASE_URL: ${{ secrets.NEXT_PUBLIC_SERVER_BASE_URL }}
        shell: bash
        run: |
          SERVER_BASE_URL_WITHOUT_HTTPS="${DEV_SERVER_BASE_URL//https:\/\//}"
          SAFE_BRANCH="$(echo $GIT_BRANCH | tr "[:punct:]" "-")"
          SERVER_BASE_URL="https://${SAFE_BRANCH}.${SERVER_BASE_URL_WITHOUT_HTTPS}"
          echo "server-base-url=$SERVER_BASE_URL" >> $GITHUB_OUTPUT

  cleanup-auth:
    runs-on: ubuntu-latest
    environment: dev
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Delete cognito urls
        uses: ./.github/actions/delete-cognito-urls
        with:
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          base-url: ${{ needs.setup.outputs.server-base-url }}
          pr-number: ${{ github.event.pull_request.number ||  github.event.inputs.pull_request }}
          cognito-client-id: ${{ secrets.COGNITO_CLIENT_ID }}
          cognito-user-pool-id: ${{ secrets.COGNITO_USER_POOL_ID }}

  cleanup-network:
    runs-on: ubuntu-latest
    environment: dev
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Delete Networking Components
        uses: ./.github/actions/delete-preview-network
        with:
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          base-url: ${{ needs.setup.outputs.server-base-url }}
          pr-number: ${{ github.event.pull_request.number || github.event.inputs.pull_request }}

  cleanup-service:
    runs-on: ubuntu-latest
    environment: dev
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Delete ECS Services
        uses: ./.github/actions/delete-preview-ecs
        with:
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          pr-number: ${{ github.event.pull_request.number || github.event.inputs.pull_request }}
