on:
  push:
    branches:
      - main
    paths:
      - \server\main\resources\schemas\claim-v1.0-all-fields.json
jobs:
  slackNotification:
    name: Slack Schema Change Notification
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "C4DLJMWAD-1659721810.263149"
          # For posting a simple plain text message
          slack-message: "Nava Team, the schema file has been altered: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
