on:
  push:
    branches:
      - 533-ab-schema-github-action-on-merging
    paths:
      - "server/src/main/resources/schemas/claim-v1.0-all-fields.json"
jobs:
  slackNotification:
    name: Slack Schema Change Notification
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a simple plain text message
          payload: |
            {
              "text": "Nava team, the schema claim-v1.0.all-fields has been changed. See this commit for details: \n${{github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Nava team, the schema claim-v1.0.all-fields has been changed. See this commit for details: \n${{github.event.head_commit.url }}"
                  }
                }
              ]
            }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
